//action constants
export const FETCH_ALL_STATS_SUCCESS = "FETCH_ALL_STATS_SUCCESS";
export const FETCH_ALL_STATS_REQUEST = "FETCH_ALL_STATS_REQUEST";
export const FETCH_ALL_STATS_FAILURE = "FETCH_ALL_STATS_FAILURE";
